version: '3.8'

services:
  postgres:
    container_name: timemanager-database
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: $POSTGRES_DATA
    volumes:
      - postgres:$POSTGRES_DATA
    ports:
      - "5432:5432"
    restart: unless-stopped

  api:
    container_name: timemanager-api
    image: ghcr.io/gabinrn/time-manager-api:master
    volumes : 
        - ../theme01:/api
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATA: $POSTGRES_DATA
    ports:
      - "4000:4000" 
    depends_on: 
      - postgres

  front:
    container_name: timemanager-front
    image: ghcr.io/gabinrn/time-manager-front:master
    volumes:
      - ../webinterface:/app
    ports:
      - "8080:8080"
    depends_on:
      - api
  
volumes:
  postgres: