version: '3.8'

services:
  api:
    container_name: timemanager-api
    build: ../theme01/
    volumes:
      - ../theme01:/api
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    container_name: timemanager-database
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: $POSTGRES_DATA
    volumes:
      - postgres:$POSTGRES_DATA
    ports:
      - "5432:5432"
    restart: unless-stopped

  front:
    container_name: timemanager-front
    build: ../webinterface/
    volumes:
      - ../webinterface:/app
    ports:
      - "8080:8080"
    depends_on:
      - api
  
volumes:
  postgres: